name: Fabric CI

on:
  push:
    branches: [ main, development]
  pull_request:
    branches: [ main, development ]

jobs:
  buildAndRunForSomeVersions:
    name: Run tests for ${{ matrix.minecraftVersion }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        minecraftVersion:
          - 1.19
          - 1.19.1
          - 1.19.2
          - 1.19.3
          - 1.19.4

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: Geometrically/fabric-test-runner@v1
        id: testRunner
        with:
          minecraftVersion: ${{ matrix.minecraftVersion }}
      - uses: actions/upload-artifact@v1
        with:
          name: Builds
          path: build/libs
