name: Fabric CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  buildAndRunForSomeVersions:
    name: Run tests for 1.19.x
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: Geometrically/fabric-test-runner@v1
        id: testRunner
        with:
          minecraftVersion: 1.19.x
      - uses: actions/upload-artifact@v1
        with:
          name: Builds
          path: build/libs
